accumulate_grad_batches: 1 # Gradient accumulation every n batches
max_epochs: 200
                           # accelerator: ddp # Automatically set if gpus > 1
log_every_n_steps: 50
limit_train_batches: 1.0   # train on full dataset, can be used to toggle quick run
limit_val_batches: 1.0     # validate on full dataset, can be used to toggle quick run
accelerator: 'gpu'
devices: [ 0 ]
precision: '16-mixed'
default_root_dir: out/${dataset._name_}/${model._name_}/${experiment_name}/