name: long-transformers-exp

channels:
  - pytorch
  - nvidia
  - conda-forge

dependencies:
  - python==3.11
  - conda-forge::transformers==4.35.0
  - conda-forge::jupyterlab==4.0.8
  - conda-forge::sentence-transformers==2.2.2
  - pytorch::pytorch==2.2.0
  - pytorch::pytorch-cuda
  - pytorch::torchvision==0.17.0
  - conda-forge::pytorch-lightning==2.1.0
  - conda-forge::torchmetrics==1.2.0
  - conda-forge::opt-einsum=3.3.0
