name: long-transformers

channels:
  - pytorch
  - nvidia
  - conda-forge

dependencies:
  - python==3.10
  - conda-forge::transformers==4.35.0
  - conda-forge::jupyterlab==4.0.8
  - conda-forge::sentence-transformers==2.2.2
  - conda-forge::numpy==1.26.0
  - pytorch::pytorch==2.1.0
  - pytorch::pytorch-cuda
  - pytorch::torchvision==0.16.0
  - conda-forge::pytorch-lightning==2.1.0
  - conda-forge::torchmetrics==1.2.0
  - conda-forge::opt-einsum==3.3.0
  - conda-forge::hydra-core==1.3.2
