_name_: sequential
schedulers:
  warmup:
    _name_: linear
    step_ratio: 0.1
    start_factor: 1.0e-8
    end_factor: 1.0
  cosine:
    _name_: cosine
    step_ratio: 0.9
    T_0: 1
    T_mult: 2
    eta_min: 0.0