# @package _global_
defaults:
  - /task:
    - classification

task:
  classification:
    num_classes: 2
    head_params:
      concat_consecutive: true

dataset:
  _name_: text-retrieval
  data_path: datasets/text_retrieval
  batch_size: 16
  max_len: 4096
  random_start: false
  add_cls_token: false
  pin_memory: true
  num_workers: 6