denoise:
  _name_: denoise
  num_embeddings: ???  # should be equal to your vocab size
  mask_token_id: ???
  mask_ratio: 0.3
  random_ratio: 0.333
  head_params:
    ff_dim: 0
    num_hidden_layers: 0
    dropout_p: 0.0
    reduction_method: none