# @package _global_
defaults:
  - _self_
  - /callback:
    - model_checkpoint
    - early_stopping
    - learning_rate_monitor

# Set `~wandb` or `wandb=null` or `wandb.mode=disabled` to disable logging
wandb:
  project: lra-paper
  group: ""
  job_type: training
  mode: online # choices=['online', 'offline', 'disabled']
  save_dir: ./out/logs/wandb
  id: null # pass correct id to resume experiment!
  # Below options should not need to be specified
  name: ''
  log_model: true
  # prefix: ""
  # tags: []

hydra:
  run:
    dir: ./out/logs/hydra/${now:%Y-%m-%d}/${now:%H-%M-%S-%f}