# @package _global_
defaults:
  - _self_

# Set `~wandb` or `wandb=null` or `wandb.mode=disabled` to disable logging
wandb:
  project: lra-paper
  group: ""
  job_type: training
  mode: online # choices=['online', 'offline', 'disabled']
  save_dir: null
  id: null # pass correct id to resume experiment!
  # Below options should not need to be specified
  entity: ''  # set to name of your wandb team or just remove it
  name: ''
  # log_model: False
  # prefix: ""
  # job_type: "train"
  # tags: []

# hydra:
#   run:
#     dir: ./out/${now:%Y-%m-%d}/${now:%H-%M-%S-%f}